import type { Vehicle } from "./types";

/**
 * SAMPLE inventory — illustrative only, used to build and demo the listing +
 * detail templates and the filter UI. These are NOT real vehicles for sale.
 * When inventory goes live, this file is replaced by a real source adapter
 * (see source.ts). Images are intentionally empty → branded placeholder.
 */
export const mockVehicles: Vehicle[] = [
  {
    id: "1",
    slug: "2019-toyota-camry-se",
    year: 2019,
    make: "Toyota",
    model: "Camry",
    trim: "SE",
    bodyStyle: "Sedan",
    price: 19450,
    mileage: 58200,
    exteriorColor: "Celestial Silver",
    interiorColor: "Black",
    transmission: "8-Speed Automatic",
    drivetrain: "FWD",
    fuelType: "Gasoline",
    engine: "2.5L 4-Cyl",
    mpgCity: 28,
    mpgHighway: 39,
    features: ["Apple CarPlay", "Backup Camera", "Lane Departure Alert", "Adaptive Cruise"],
    description:
      "A clean, fuel-efficient sedan that's ideal for commuting and families alike. Well-maintained with the reliability the Camry is known for.",
    images: [],
    status: "available",
  },
  {
    id: "2",
    slug: "2020-honda-cr-v-ex",
    year: 2020,
    make: "Honda",
    model: "CR-V",
    trim: "EX",
    bodyStyle: "SUV",
    price: 24990,
    mileage: 46100,
    exteriorColor: "Modern Steel",
    interiorColor: "Gray",
    transmission: "CVT Automatic",
    drivetrain: "AWD",
    fuelType: "Gasoline",
    engine: "1.5L Turbo 4-Cyl",
    mpgCity: 27,
    mpgHighway: 32,
    features: ["Sunroof", "Heated Seats", "Apple CarPlay", "Honda Sensing", "Blind Spot Monitor"],
    description:
      "Spacious, efficient, and dependable — the CR-V is one of the most popular compact SUVs for good reason. Roomy cargo and a smooth ride.",
    images: [],
    status: "available",
  },
  {
    id: "3",
    slug: "2018-ford-f-150-xlt",
    year: 2018,
    make: "Ford",
    model: "F-150",
    trim: "XLT",
    bodyStyle: "Truck",
    price: 28750,
    mileage: 72400,
    exteriorColor: "Oxford White",
    interiorColor: "Medium Earth Gray",
    transmission: "10-Speed Automatic",
    drivetrain: "4WD",
    fuelType: "Gasoline",
    engine: "5.0L V8",
    mpgCity: 17,
    mpgHighway: 23,
    features: ["Tow Package", "Backup Camera", "Bluetooth", "Bed Liner", "Running Boards"],
    description:
      "Capable and ready to work or play. This F-150 XLT pairs the proven 5.0L V8 with 4WD and a factory tow package.",
    images: [],
    status: "available",
  },
  {
    id: "4",
    slug: "2021-nissan-sentra-sv",
    year: 2021,
    make: "Nissan",
    model: "Sentra",
    trim: "SV",
    bodyStyle: "Sedan",
    price: 17900,
    mileage: 39800,
    exteriorColor: "Gun Metallic",
    interiorColor: "Charcoal",
    transmission: "CVT Automatic",
    drivetrain: "FWD",
    fuelType: "Gasoline",
    engine: "2.0L 4-Cyl",
    mpgCity: 29,
    mpgHighway: 39,
    features: ["Apple CarPlay", "Android Auto", "Safety Shield 360", "Push-Button Start"],
    description:
      "A great first car or commuter — low miles, modern tech, and excellent fuel economy in a sharp-looking package.",
    images: [],
    status: "available",
  },
  {
    id: "5",
    slug: "2017-chevrolet-equinox-lt",
    year: 2017,
    make: "Chevrolet",
    model: "Equinox",
    trim: "LT",
    bodyStyle: "SUV",
    price: 15250,
    mileage: 88600,
    exteriorColor: "Summit White",
    interiorColor: "Jet Black",
    transmission: "6-Speed Automatic",
    drivetrain: "FWD",
    fuelType: "Gasoline",
    engine: "1.5L Turbo 4-Cyl",
    mpgCity: 26,
    mpgHighway: 32,
    features: ["Backup Camera", "Bluetooth", "Remote Start", "Roof Rails"],
    description:
      "An affordable, comfortable SUV with room for the whole family and a budget-friendly price.",
    images: [],
    status: "available",
  },
  {
    id: "6",
    slug: "2020-jeep-grand-cherokee-limited",
    year: 2020,
    make: "Jeep",
    model: "Grand Cherokee",
    trim: "Limited",
    bodyStyle: "SUV",
    price: 27400,
    mileage: 61300,
    exteriorColor: "Diamond Black",
    interiorColor: "Black",
    transmission: "8-Speed Automatic",
    drivetrain: "4WD",
    fuelType: "Gasoline",
    engine: "3.6L V6",
    mpgCity: 19,
    mpgHighway: 26,
    features: ["Leather Seats", "Navigation", "Heated/Ventilated Seats", "Panoramic Sunroof", "4WD"],
    description:
      "Premium comfort meets genuine capability. Loaded Limited trim with leather, nav, and a panoramic roof.",
    images: [],
    status: "pending",
  },
  {
    id: "7",
    slug: "2019-hyundai-elantra-sel",
    year: 2019,
    make: "Hyundai",
    model: "Elantra",
    trim: "SEL",
    bodyStyle: "Sedan",
    price: 14600,
    mileage: 67900,
    exteriorColor: "Phantom Black",
    interiorColor: "Gray",
    transmission: "6-Speed Automatic",
    drivetrain: "FWD",
    fuelType: "Gasoline",
    engine: "2.0L 4-Cyl",
    mpgCity: 28,
    mpgHighway: 37,
    features: ["Apple CarPlay", "Blind Spot Monitor", "Backup Camera", "Alloy Wheels"],
    description:
      "Value-packed and easy on gas. A dependable sedan with the balance of warranty-era reliability and modern features.",
    images: [],
    status: "available",
  },
  {
    id: "8",
    slug: "2021-toyota-rav4-xle",
    year: 2021,
    make: "Toyota",
    model: "RAV4",
    trim: "XLE",
    bodyStyle: "SUV",
    // price intentionally omitted → demonstrates the "Call for price" path
    mileage: 41200,
    exteriorColor: "Magnetic Gray",
    interiorColor: "Black",
    transmission: "8-Speed Automatic",
    drivetrain: "AWD",
    fuelType: "Gasoline",
    engine: "2.5L 4-Cyl",
    mpgCity: 27,
    mpgHighway: 34,
    features: ["Sunroof", "Apple CarPlay", "Toyota Safety Sense", "Power Liftgate", "AWD"],
    description:
      "The do-everything SUV. Efficient, roomy, and holds its value — a smart pick for Florida roads and road trips alike.",
    images: [],
    status: "available",
  },
];
